<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Html2TextException'                         => __DIR__ . '/src/html2text.php',
    'MssMessage\Listener\Data\Listener'          => __DIR__ . '/src/MssMessage/Listener/Data/Listener.php',
    'MssMessage\Listener\Data\StandardListener'  => __DIR__ . '/src/MssMessage/Listener/Data/StandardListener.php',
    'MssMessage\Listener\Queue\Listener'         => __DIR__ . '/src/MssMessage/Listener/Queue/Listener.php',
    'MssMessage\Listener\Queue\StandardListener' => __DIR__ . '/src/MssMessage/Listener/Queue/StandardListener.php',
    'MssMessage\Entity\ContactType'              => __DIR__ . '/src/MssMessage/Entity/ContactType.php',
    'MssMessage\Entity\MessageLayout'            => __DIR__ . '/src/MssMessage/Entity/MessageLayout.php',
    'MssMessage\Entity\Message'                  => __DIR__ . '/src/MssMessage/Entity/Message.php',
    'MssMessage\Entity\MessageSent'              => __DIR__ . '/src/MssMessage/Entity/MessageSent.php',
    'MssMessage\Entity\MessageType'              => __DIR__ . '/src/MssMessage/Entity/MessageType.php',
    'MssMessage\Form\Definition\Layout'          => __DIR__ . '/src/MssMessage/Form/Layout.php',
    'MssMessage\Controller\LayoutsController'    => __DIR__ . '/src/MssMessage/Controller/LayoutsController.php',
    'MssMessage\Controller\MessageController'    => __DIR__ . '/src/MssMessage/Controller/MessageController.php',
    'MssMessage\Service\Sender'                  => __DIR__ . '/src/MssMessage/Service/Sender.php',
    'MssMessage\Repository\MessageLayout'        => __DIR__ . '/src/MssMessage/Repository/MessageLayout.php',
    'MssMessage\Repository\Message'              => __DIR__ . '/src/MssMessage/Repository/Message.php',
    'MssMessage\Module'                          => __DIR__ . '/Module.php',
);